baseURL = ''
languageCode = 'ru-ru'
title = 'Турецкий с Анатолием'
theme = 'my'
defaultContentLanguage = 'ru'

[params]
  githubRepo = "https://github.com/antelman107/turkish"
  githubBranch = "main"

[languages]
    [languages.ru]
      weight = 1
      languageCode = 'ru-ru'
